[package]
name = "orpa"
version = "0.1.0"
authors = ["Alex Sayers <alex.sayers@gmail.com>"]
description = "A tool for enforcing code review requirements"
license = "unlicense"

[dependencies]
clap = "2.32.0"
env_logger = "0.5.13"
failure = "0.1.2"
git2 = { git = "https://github.com/alexcrichton/git2-rs.git" }
glob = "0.2.11"
itertools = "0.7.8"
log = "0.4.5"
structopt = "0.2.10"
